apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes[0] }}
  local:
    path: {{ .Values.persistentVolume.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistentVolume.nodeAffinity.required.nodeSelectorTerms[0].matchExpressions[0].values[0] }}