verticaDB:
  subclusters:
      resources:
        limits:
          cpu: "3"
          memory: "30Gi"
        requests:
          cpu: "2"
          memory: "10Gi"


persistentVolume:
  spec:
    storageClassName: rook-ceph-block
    capacity:
      storage: 100Gi

namespace: vertica
persistentVolumeClaim:
  spec:
    storageClassName: rook-ceph-block
    resources:
      requests:
        storage: 100Gi
