apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verticadb-pvc
  namespace: vertica
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.spec.resources.requests.storage }}
