# apiVersion: vertica.com/v1
# kind: VerticaDB
# metadata:
#   name: verticadb
#   namespace: vertica
# spec:
#   subclusters:
#     - name: sc1
#       size: 3
apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: {{ .Values.verticaDB.metadata.name }}
  namespace: {{ .Values.verticaDB.metadata.namespace }}
spec:
  subclusters:
    - name: {{ .Values.verticaDB.subclusters[0].name }}
      size: {{ .Values.verticaDB.subclusters[0].size }}
      resources:
        limits:
          cpu: "{{ .Values.verticaDB.subclusters[0].resources.limits.cpu }}"
          memory: "{{ .Values.verticaDB.subclusters[0].resources.limits.memory }}"
        requests:
          cpu: "{{ .Values.verticaDB.subclusters[0].resources.requests.cpu }}"
          memory: "{{ .Values.verticaDB.subclusters[0].resources.requests.memory }}"
  communal:
    path: "/mnt/home/test/vertica1"
  volumeMounts:
    - name: communal-storage
      mountPath: "/mnt/home/test/vertica1"
  volumes:
    - name: communal-storage
      persistentVolumeClaim:
        claimName: verticadb-pvc
