apiVersion: v1
kind: PersistentVolume
metadata:
  name: verticadb-pv
spec:
  storageClassName: rook-ceph-block
  capacity:
    storage: {{ .Values.persistentVolume.spec.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/home/test/vertica3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloudlyte
