apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verticadb-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.spec.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.spec.resources.requests.storage }}
