apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: verticadb
  namespace: vertica
spec:
  subclusters:
    - name: sc1
      size: 3
      resources:
        limits:
          cpu: {{ .Values.verticaDB.subclusters.resources.limits.cpu }}
          memory: {{ .Values.verticaDB.subclusters.resources.limits.memory }}
        requests:
          cpu: {{ .Values.verticaDB.subclusters.resources.requests.cpu }}
          memory: {{ .Values.verticaDB.subclusters.resources.requests.memory }}
  communal:
    path: "/mnt/home/test/vertica3"
  volumeMounts:
    - name: communal-storage
      mountPath: "/mnt/home/test/vertica3"
    - name: backup-configmap
      mountPath: /etc/vertica/backup
      subPath: backup.ini
  volumes:
    - name: communal-storage
      persistentVolumeClaim:
        claimName: verticadb-pvc
    - name: backup-configmap
      configMap:
        name: backup-configmap
